In [3]:
from CAN_processor import load_dbc, load_mf4, decode_obd2,filter_obd2, plot_signals

DBC_PATH = r"C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\obd2-pack-v5\obd2-dbc\CSS-Electronics-11-bit-OBD2-v2.2.dbc"
MF4_PATH = r"C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\obd2-pack-v5\obd2-sample-data\Renault Kadjar 2020\00000001.MF4"

db = load_dbc(DBC_PATH)
raw_df = load_mf4(MF4_PATH)

obd2_df = filter_obd2(raw_df)

decoded_df = decode_obd2(obd2_df, db)

signals_to_plot = [
    'S01PID05_EngineCoolantTemp',
    'S01PID0C_EngineRPM',
    'S01PID0D_VehicleSpeed',
    'S01PID10_MAFAirFlowRate',
    'S01PID11_ThrottlePosition'
]

plotting = plot_signals(decoded_df, signals_to_plot, title='Renault Kadjar OBD2 Data')

DBC loaded : C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\obd2-pack-v5\obd2-dbc\CSS-Electronics-11-bit-OBD2-v2.2.dbc
Messages : 1
MF4 loaded : C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\obd2-pack-v5\obd2-sample-data\Renault Kadjar 2020\00000001.MF4
Total frames  : 3077765
Time range    : 0.0s → 2068.4593s
OBD2 Frames : 5458  (ID= 2024)
Decoded Signals : 5458
Signals found : ['Length', 'Response', 'Service', 'S01PID', 'S01PID0C_EngineRPM', 'S01PID0D_VehicleSpeed', 'S01PID10_MAFAirFlowRate', 'S01PID11_ThrottlePosition', 'S01PID5E_EngineFuelRate', 'S01PID5C_EngineOilTemp', 'S01PID62_ActualEngTorqPct', 'S01PID42_ControlModuleVolt', 'S01PID33_AbsBaroPres', 'S01PID04_CalcEngineLoad', 'S01PID0F_IntakeAirTemperature', 'S01PID2F_FuelTankLevel', 'S01PID05_EngineCoolantTemp', 'S01PID0B_IntakeManiAbsPress']

In [18]:
decoded_df

,Length,Response,Service,S01PID,S01PID05_EngineCoolantTemp,S01PID0C_EngineRPM,S01PID0D_VehicleSpeed,S01PID10_MAFAirFlowRate,S01PID11_ThrottlePosition,S01PID00_PIDsSupported_01_20,S01PID40_PIDsSupported_41_60
timestamps,,,,,,,,,,,
0.02960,3,4,1,5,18.0,NaN,NaN,NaN,NaN,NaN,NaN
0.09115,4,4,1,12,NaN,1178.0,NaN,NaN,NaN,NaN,NaN
0.11150,3,4,1,13,NaN,NaN,0.0,NaN,NaN,NaN,NaN
0.13200,4,4,1,16,NaN,NaN,NaN,4.67,NaN,NaN,NaN
0.15295,3,4,1,17,NaN,NaN,NaN,NaN,18.43152,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1327.84645,3,4,1,17,NaN,NaN,NaN,NaN,18.43152,NaN,NaN
1327.98605,4,4,1,12,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1328.00630,3,4,1,13,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1328.02675,4,4,1,16,NaN,NaN,NaN,0.21,NaN,NaN,NaN
1328.04315,3,4,1,17,NaN,NaN,NaN,NaN,18.43152,NaN,NaN

In [19]:
raw_df

,BusChannel,ID,CAN_DataFrame.CAN_DataFrame.IDE,CAN_DataFrame.CAN_DataFrame.DLC,DataLength,DataBytes,Dir
timestamps,,,,,,,
0.00000,1.0,1102,0.0,8,8.0,"[135, 47, 250, 225, 18, 64, 47, 63]",0.0
0.00160,1.0,786,0.0,8,8.0,"[85, 0, 12, 71, 254, 32, 0, 57]",0.0
0.00175,1.0,224,0.0,5,5.0,"[203, 127, 252, 127, 239, 0, 0, 0]",0.0
0.00200,1.0,225,0.0,8,8.0,"[255, 255, 255, 255, 255, 255, 100, 161]",0.0
0.00225,1.0,665,0.0,8,8.0,"[255, 255, 255, 24, 16, 24, 255, 240]",0.0
...,...,...,...,...,...,...,...
2068.45805,1.0,413,0.0,6,6.0,"[56, 127, 255, 255, 255, 8, 0, 0]",0.0
2068.45860,1.0,346,0.0,6,6.0,"[72, 160, 39, 216, 0, 0, 0, 0]",0.0
2068.45885,1.0,348,0.0,8,8.0,"[42, 48, 56, 179, 131, 42, 99, 0]",0.0
2068.45910,1.0,349,0.0,8,8.0,"[40, 46, 130, 240, 24, 72, 68, 254]",0.0
2068.45930,1.0,350,0.0,8,8.0,"[56, 51, 136, 52, 146, 247, 113, 153]",0.0

In [15]:
obd2_dataf

,BusChannel,ID,CAN_DataFrame.CAN_DataFrame.IDE,CAN_DataFrame.CAN_DataFrame.DLC,DataLength,DataBytes,Dir,CAN_DataFrame.CAN_DataFrame.EDL,CAN_DataFrame.CAN_DataFrame.BRS
timestamps,,,,,,,,,
0.02960,1,2024,0,8,8,"[3, 65, 5, 58, 0, 0, 0, 0]",0,0,0
0.09115,1,2024,0,8,8,"[4, 65, 12, 18, 104, 0, 0, 0]",0,0,0
0.11150,1,2024,0,8,8,"[3, 65, 13, 0, 0, 0, 0, 0]",0,0,0
0.13200,1,2024,0,8,8,"[4, 65, 16, 1, 211, 0, 0, 0]",0,0,0
0.15295,1,2024,0,8,8,"[3, 65, 17, 47, 0, 0, 0, 0]",0,0,0
...,...,...,...,...,...,...,...,...,...
1327.84645,1,2024,0,8,8,"[3, 65, 17, 47, 0, 0, 0, 0]",0,0,0
1327.98605,1,2024,0,8,8,"[4, 65, 12, 0, 0, 0, 0, 0]",0,0,0
1328.00630,1,2024,0,8,8,"[3, 65, 13, 0, 0, 0, 0, 0]",0,0,0
1328.02675,1,2024,0,8,8,"[4, 65, 16, 0, 21, 0, 0, 0]",0,0,0
1328.04315,1,2024,0,8,8,"[3, 65, 17, 47, 0, 0, 0, 0]",0,0,0