In [5]:
from CAN_processor import load_dbc, load_mf4, decode_obd2,filter_obd2, plot_signals, file_save

DBC_PATH = r"C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\obd2-pack-v5\obd2-dbc\CSS-Electronics-11-bit-OBD2-v2.2.dbc"
MF4_PATH = r"C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\obd2-pack-v5\obd2-sample-data\Mercedes E350 2010\00000001.MF4"

db = load_dbc(DBC_PATH)
raw_df = load_mf4(MF4_PATH)

obd2_df = filter_obd2(raw_df)

decoded_df = decode_obd2(obd2_df, db)

signals_to_plot = [
'S01PID10_MAFAirFlowRate', 'S01PID0B_IntakeManiAbsPress', 'S01PID0C_EngineRPM', 'S01PID0D_VehicleSpeed', 'S01PID11_ThrottlePosition', 'S01PID05_EngineCoolantTemp', 'S01PID2F_FuelTankLevel'
]

plot_signals(decoded_df, signals_to_plot, title='Mercedes E350 OBD2 Data')

# file_save(decoded_df)

DBC loaded : C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\obd2-pack-v5\obd2-dbc\CSS-Electronics-11-bit-OBD2-v2.2.dbc
Messages : 1
MF4 loaded : C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\obd2-pack-v5\obd2-sample-data\Mercedes E350 2010\00000001.MF4
Total frames  : 210712
Time range    : 0.0s → 309.49475000000007s
OBD2 Frames : 8070  (ID= 2024)
Decoded Signals : 8070
Signals found : ['Length', 'Response', 'Service', 'S01PID', 'S01PID10_MAFAirFlowRate', 'S01PID0B_IntakeManiAbsPress', 'S01PID0C_EngineRPM', 'S01PID0D_VehicleSpeed', 'S01PID11_ThrottlePosition', 'S01PID05_EngineCoolantTemp', 'S01PID00_PIDsSupported_01_20', 'S01PID20_PIDsSupported_21_40', 'S01PID40_PIDsSupported_41_60', 'S01PID60_PIDsSupported_61_80', 'S01PID2F_FuelTankLevel']

In [2]:
decoded_df

,Length,Response,Service,S01PID,S01PID10_MAFAirFlowRate,S01PID0B_IntakeManiAbsPress,S01PID0C_EngineRPM,S01PID0D_VehicleSpeed,S01PID11_ThrottlePosition,S01PID05_EngineCoolantTemp,S01PID00_PIDsSupported_01_20,S01PID20_PIDsSupported_21_40,S01PID40_PIDsSupported_41_60,S01PID60_PIDsSupported_61_80,S01PID2F_FuelTankLevel
timestamps,,,,,,,,,,,,,,,
0.11915,4,4,1,16,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.23915,3,4,1,11,NaN,94.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.25945,4,4,1,12,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.27915,3,4,1,13,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.29955,4,4,1,16,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309.30195,3,4,1,13,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309.32175,4,4,1,16,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309.34170,3,4,1,17,NaN,NaN,NaN,NaN,89.02032,NaN,NaN,NaN,NaN,NaN,NaN
309.46170,3,4,1,11,NaN,95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309.48175,4,4,1,12,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
raw_df

,BusChannel,ID,IDE,DLC,DataLength,DataBytes,Dir,EDL,BRS
timestamps,,,,,,,,,
0.00000,1,1024,0,8,8,"[254, 0, 4, 2, 0, 0, 0, 5]",0,0,0
0.00395,1,643,0,8,8,"[86, 15, 8, 3, 192, 255, 63, 255]",0,0,0
0.00430,1,1886,0,8,8,"[0, 129, 0, 45, 24, 8, 8, 8]",0,0,0
0.00470,1,1902,0,8,8,"[0, 0, 0, 0, 0, 0, 0, 0]",0,0,0
0.00895,1,643,0,8,8,"[86, 15, 8, 3, 192, 255, 63, 255]",0,0,0
...,...,...,...,...,...,...,...,...,...
309.48875,1,1886,0,8,8,"[0, 129, 0, 45, 24, 24, 24, 24]",0,0,0
309.49185,1,5,0,8,8,"[0, 0, 240, 0, 29, 0, 112, 93]",0,0,0
309.49230,1,301,0,8,8,"[1, 15, 0, 0, 200, 161, 232, 59]",0,0,0
309.49265,1,3,0,8,8,"[16, 0, 16, 0, 4, 255, 192, 47]",0,0,0
309.49475,1,1894,0,8,8,"[0, 0, 0, 0, 0, 0, 4, 11]",0,0,0

In [4]:
obd2_dataf

NameError: name 'obd2_dataf' is not defined